const translations = {
    arabic: {
        title: "لعبة أسرع كتابة",
        gameTitle: "🎯 لعبة أسرع كتابة",
        arabic: "العربية",
        english: "الإنجليزية",
        french: "الفرنسية",
        spanish: "الإسبانية",
        startGame: "ابدأ اللعبة",
        playing: "جاري اللعب...",
        timeLabel: "الوقت (ثانية)",
        wpmLabel: "كلمة/دقيقة",
        accuracyLabel: "الدقة",
        errorsLabel: "الأخطاء",
        welcomeMessage: 'اضغط على "ابدأ اللعبة" لبدء التحدي!',
        placeholder: 'ابدأ بالكتابة هنا...',
        congrats: "🎉 تهانينا! لقد أنهيت التحدي",
        finalTimeLabel: "الوقت النهائي",
        finalWpmLabel: "كلمة/دقيقة",
        finalAccuracyLabel: "الدقة النهائية",
        finalErrorsLabel: "الأخطاء",
        playAgain: "لعب مرة أخرى",
        fetchingText: "جاري تحميل النص...",
        modePassage: "النص الكامل",
        modeTimed: "مؤقت",
        time15: "١٥ ثانية",
        time30: "٣٠ ثانية",
        time60: "٦٠ ثانية",
        time120: "١٢٠ ثانية",
        copyResults: "نسخ النتائج",
        shareResults: "مشاركة النتائج",
        showStats: "إظهار الإحصائيات",
        modeLabel: "الوضع:",
        hideStats: "إخفاء الإحصائيات",
        punctuation: "علامات الترقيم",
        modeCustom: "نص مخصص",
        suddenDeath: "الموت المفاجئ",
        modeWords: "عدد الكلمات",
        words10: "10 كلمات",
        words25: "25 كلمة",
        words50: "50 كلمة",
        words100: "100 كلمة"
    },
    english: {
        title: "Typing Speed Test",
        gameTitle: "🎯 Typing Speed Test",
        startGame: "Start Game",
        playing: "Playing...",
        timeLabel: "Time (s)",
        wpmLabel: "WPM",
        accuracyLabel: "Accuracy",
        errorsLabel: "Errors",
        welcomeMessage: 'Click "Start Game" to begin the challenge!',
        placeholder: 'Start typing here...',
        congrats: "🎉 Congratulations! You completed the challenge",
        finalTimeLabel: "Final Time",
        finalWpmLabel: "WPM",
        finalAccuracyLabel: "Final Accuracy",
        finalErrorsLabel: "Errors",
        playAgain: "Play Again",
        fetchingText: "Fetching text...",
        modePassage: "Full Passage",
        modeTimed: "Timed",
        time15: "15s",
        time30: "30s",
        time60: "60s",
        time120: "120s",
        copyResults: "Copy Results",
        shareResults: "Share Results",
        showStats: "Show Stats",
        modeLabel: "Mode:",
        arabic: "Arabic",
        english: "English",
        french: "French",
        spanish: "Spanish",
        hideStats: "Hide Stats",
        punctuation: "Punctuation",
        modeCustom: "Custom",
        suddenDeath: "Sudden Death",
        modeWords: "Words",
        words10: "10 words",
        words25: "25 words",
        words50: "50 words",
        words100: "100 words"
    },
    french: {
        title: "Test de vitesse de frappe",
        gameTitle: "🎯 Test de vitesse de frappe",
        arabic: "Arabe",
        english: "Anglais",
        french: "Français",
        spanish: "Espagnol",
        startGame: "Démarrer le test",
        playing: "En cours...",
        timeLabel: "Temps (s)",
        wpmLabel: "Mots/minute",
        accuracyLabel: "Précision",
        errorsLabel: "Fautes",
        welcomeMessage: 'Cliquez sur "Démarrer le test" pour commencer le défi !',
        placeholder: 'Commencez à taper ici...',
        congrats: "🎉 Félicitations ! Vous avez terminé le défi",
        finalTimeLabel: "Temps final",
        finalWpmLabel: "Mots/minute",
        finalAccuracyLabel: "Précision finale",
        finalErrorsLabel: "Fautes",
        playAgain: "Rejouer",
        fetchingText: "Chargement du texte...",
        modePassage: "Texte complet",
        modeTimed: "Minuterie",
        time15: "15s",
        time30: "30s",
        time60: "60s",
        time120: "120s",
        copyResults: "Copier les résultats",
        shareResults: "Partager les résultats",
        toggleStats: "Masquer les statistiques",
        showStats: "Afficher les statistiques",
        modeLabel: "Mode :",
        hideStats: "Masquer les statistiques",
        punctuation: "Ponctuation",
        modeCustom: "Personnalisé",
        suddenDeath: "Mort subite",
        modeWords: "Mots",
        words10: "10 mots",
        words25: "25 mots",
        words50: "50 mots",
        words100: "100 mots"
    },
    spanish: {
        title: "Prueba de velocidad de escritura",
        gameTitle: "🎯 Prueba de velocidad de escritura",
        arabic: "Árabe",
        english: "Inglés",
        french: "Francés",
        spanish: "Español",
        startGame: "Comenzar prueba",
        playing: "Jugando...",
        timeLabel: "Tiempo (s)",
        wpmLabel: "Palabras/minuto",
        accuracyLabel: "Precisión",
        errorsLabel: "Errores",
        welcomeMessage: 'Haz clic en "Comenzar prueba" para empezar el reto!',
        placeholder: 'Empieza a escribir aquí...',
        congrats: "🎉 ¡Felicidades! Has completado el reto",
        finalTimeLabel: "Tiempo final",
        finalWpmLabel: "Palabras/minuto",
        finalAccuracyLabel: "Precisión final",
        finalErrorsLabel: "Errores",
        playAgain: "Jugar de nuevo",
        fetchingText: "Cargando texto...",
        modePassage: "Texto completo",
        modeTimed: "Temporizador",
        time15: "15s",
        time30: "30s",
        time60: "60s",
        time120: "120s",
        copyResults: "Copiar resultados",
        shareResults: "Compartir resultados",
        toggleStats: "Ocultar estadísticas",
        showStats: "Mostrar estadísticas",
        modeLabel: "Modo:",
        hideStats: "Ocultar estadísticas",
        punctuation: "Puntuación",
        modeCustom: "Personalizado",
        suddenDeath: "Muerte súbita",
        modeWords: "Palabras",
        words10: "10 palabras",
        words25: "25 palabras",
        words50: "50 palabras",
        words100: "100 palabras"
    }
}; 